version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080 # For application
      - 2345:2345 # For dlv
    security_opt:
      - apparmor:unconfined # ref: https://github.com/derekparker/delve/blob/master/Documentation/faq.md#how-do-i-use-delve-with-docker
